name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: v4hn/ros-deb-builder-action@rosotest
        timeout-minutes: 350
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          DEB_REPOSITORY: |
            deb [trusted=yes] https://raw.githubusercontent.com/v4hn/ros-deb-test/jammy-one/ ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBUILD_CONF: '$verbose = 1;'
          ROSDEP_SOURCE: |
            rosdep.yaml
            https://raw.githubusercontent.com/v4hn/ros-deb-test/jammy-one/local.yaml
          SQUASH_HISTORY: false
          CONTINUE_ON_ERROR: true
          PUSH_ON_ERROR: true
